### ISSUE TITLE
Sched2 treading detaches and run forever

### ISSUE THREAD

**Issue by sukhoi47** [medecau/sched2#3]
Hi,

I have this (simplified) code:
```
import datetime
from flask import Flask
from sched2 import scheduler

# Create a scheduler
sc = scheduler()

@sc.every(10)  # Run every 10 sec
def test_sched():
    file1 = open("myfile.txt", "a")
    L = f'\nExecuted at {str(datetime.datetime.utcnow())}'
    file1.writelines(L)
    file1.close()

# Run the scheduler
sc.run()


app = Flask(__name__)

@app.route('/')
# ‘/’ URL is bound with hello_world() function.
def hello_world():
   return 'Hello World'

if __name__ == '__main__':
   app.run()
```

The code runs in a Cloudlinux/Litespeed server that has its own WSGI   (called LSWSGI).

Every time the python app starts, the sched2 threading run and detaches from the main thread.
If the (main) python app is stopped, the main thread stops, but sched2 threading keeps running, and I can see that because it keep updating the **myfile.txt** every 10 seconds.
If the app is restarted, or the WSGI starts new workers, then more sched2 threading are created.
If the WSGI worker is automatically (or manually) stopped, the sched2 threading is not stopped.
And soon will have a number of sched2 threading running simultaneously, all of them saving at **myfile.txt** every 10 seconds.

Is that the normal sched2 behavior or it is a bug in my code, or Litespeed web server?

How to fix in a way that sched2 threading are stopped when the WSGI workers are stopped (automatically)?

**Comment by medecau** [comment]
Please note, I have never used LSWSGI, but have used Gunicorn and uWSGI, these should behave in similar ways.
Until I saw your ticket, I had not given much thought to threading in sched2. Issue #4 will change that.

You mention that the scheduler detaches from the main thread, but I have not observed this when testing your code.
Maybe LSWSGI works very differently from what I expect, if that is the case I cannot help much as that would out-of-scope for this project.

With that I cannot really say where the issue is, but I can offer a review of your example.

A sched2 scheduler and a flask app are setup and configured, but running it as script or as a WSGI app (gunicorn) will display the same behaviour. The scheduler will start but the app will never reply to requests. This happens because `sc.run()` blocks further processing, Python never has a chance to even instantiate the app object.

I have made some changes based on your example that I hope can help you, at least until I have time to publish changes to `sched2` based on issue #4. Note that these changes only work if the script is run directly, it won't run the scheduler inside a WSGI server.

```python
import datetime
from flask import Flask
from sched2 import scheduler
import threading


class stoppable_scheduler(scheduler):
    """A scheduler that can be stopped"""

    def __init__(self):
        super().__init__()
        # set a flag to indicate if the scheduler should be running
        self._running = True

    def stop(self):
        """Stop the scheduler"""
        # set the flag to False, we want it to stop
        self._running = False

    def run(self):
        """Run the scheduler"""
        # run the scheduler as long as we want it to
        while self._running:
            # running the scheduler withour blocking
            # guarantees that it returns if there are immediate tasks to run
            # allowing us to sleep a bit before checking the flag again
            super().run(blocking=False)
            self.delayfunc(1)


# Create a stoppable scheduler
sc = stoppable_scheduler()


@sc.every(10)  # Run every 10 seconds
def test_sched():
    # use a with statement to ensure the file is closed when we are done
    # or if an exception is raised while writing to the file
    with open("myfile.txt", "a") as file1:
        L = f"\nExecuted at {str(datetime.datetime.utcnow())}"
        file1.writelines(L)


app = Flask(__name__)


@app.route("/")
# ‘/’ URL is bound with hello_world() function.
def hello_world():
    return "Hello World"


@app.route("/show")
def show_my_file():
    """Show the contents of the file"""
    with open("myfile.txt", "r") as file:
        return f"<pre>{file.read()}</pre>"


if __name__ == "__main__":
    # Run the scheduler in a separate thread
    thread = threading.Thread(target=sc.run)
    thread.start()

    # Run the Flask app
    app.run()

    # Stop the scheduler and wait for the thread to finish
    sc.stop()
    thread.join()
```

**Comment by medecau** [comment]
I hope my previous answer helped you.

Changes noted here will be tracked in issue #4.
